language: go
go:
    - 1.2
    - 1.3
    - 1.4
    - tip
cache:
  #- apt: true

install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl bison make

script:
  - go clean
  - echo $GOPATH
  - (cd $GOPATH/src/github.com/bbiskup && git clone https://github.com/bbiskup/edify.git)
  - # Bleeding edge
  - (cd $GOPATH/src/github.com/bbiskup/edify && git checkout dev && go get ./... && go install)
  - make get-deps
  - make get-test-deps
  - make get-edifact-specs
  - go vet
  - go build
  - make check
  - make test-multi-cpu

  - # avoid excessive output
  - make bench 2> bench.log
  - make cover
  - ./edify-web run &
  - sleep 5  # Allow for initialization
  - make test-curl-1

