language: go
go:
    - 1.2
    - 1.3
    - 1.4
    - tip
cache:
  #- apt: true

install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl bison make

script:
  - go clean
  - make get-deps
  - make get-test-deps
  - go vet
  - go build
  - make check
  - make test-multi-cpu

  - # avoid excessive output
  - make bench 2> bench.log
  - make cover
  - ./edify-web &
  - make test-curl-1

