# Image for development/testing
dev:
  build: .
  volumes:
    - ./handlers:/go/src/github.com/bbiskup/edify-web/handlers
    - ./defs:/go/src/github.com/bbiskup/edify-web/defs
    - ./main.go:/go/src/github.com/bbiskup/edify-web/main.go
    - ./static:/go/src/github.com/bbiskup/edify-web/static
    - ./scripts:/go/src/github.com/bbiskup/edify-web/scripts
  ports:
    - "18002:8001"

server:
  build: .
  ports:
    - "18001:8001"
  entrypoint:
    - ./edify-web
    - run
    - -H
    - 0.0.0.0
